### ISSUE TITLE
Modify ImportingUtilitiesTests to accommodate the type change

### ISSUE THREAD

**Issue by Edvinnordling** [DD2480-group-30/Lab4OpenRefine#10]
Location:
```
main/tests/server/src/com/google/refine/importing/ImportingUtilitiesTests.java
  224, 50: parameters = ParsingUtilities.parseUrlParameters(req);
  275, 50: parameters = ParsingUtilities.parseUrlParameters(req);
  540, 50: parameters = ParsingUtilities.parseUrlParameters(req);
```

Modify the 3 methods that call `parseUrlParameters` in `ImportingUtilitiesTests` to accommodate the `Map<String, String>` type instead of the `Properties` type.

Change helper methods where needed, but create new ones if the old `Properties` version is needed elsewhere. Make sure to not change the public API.

**Comment by EliasStihl** [comment]
No test report yet
