### ISSUE TITLE
Modify CreateProjectCommand to accommodate the type change

### ISSUE THREAD

**Issue by Edvinnordling** [DD2480-group-30/Lab4OpenRefine#7]
Location:
```
main/src/com/google/refine/commands/project/CreateProjectCommand.java
  74, 54: parameters = ParsingUtilities.parseUrlParameters(request);
```

Modify the method that calls `parseUrlParameters` in `CreateProjectCommand` to accommodate the `Map<String, String>` type instead of the `Properties` type.

Change helper methods where needed, but create new ones if the old `Properties` version is needed elsewhere

Write tests for the methods changed in the test class of the file. Create the test file if it doesn't exist. Make sure to follow the existing structure for tests

**Comment by EliasStihl** [comment]
Don't know how we should update Importing Utilities without refactoring or massive code duplication

**Comment by EliasStihl** [comment]
No test report added yet

**Comment by EliasStihl** [comment]
Solved by modifying public methods by converting parameters to a map.
Also added test report
